- name: enable redis 7 version
  ansible.builtin.command: dnf module enable redis:7 -y

- name: Install redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: allow remote connection
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

- name: disable the protected mode
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "protected-mode"
    line: "protected-mode no"

- name: start and enable the service #start, enable and reload service
  ansible.builtin.service:
    name: redis
    state: restarted
    enabled: yes
