$ANSIBLE_VAULT;1.1;AES256
38363835633931646639353230333938616131356139626161393733316262646466356436623132
6335663939383839396439396261663366333837663265320a386630306530393064663730326265
66323965386232643135666165323435636163613936623561366132633935636332636239376562
3030626661373332630a326338363735633931333462396236656365363861323831643830313565
61643239663261636534633238643537616666323833303630363336636166356265633963653762
3063643965396439353161613633383532323862656663363166
