- name: run the app_setup code
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: run the python-setup code
  ansible.builtin.import_role:
    name: common
    tasks_from: python_setup.yaml

- name: run the systemd-setup code
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml
