- name: run the nginx_app_setup
  #tags:
  # - deployment #When we use tags and pass -t deployment, only the tasks that have the deployment tag will run. The other tasks will be skipped.
  ansible.builtin.import_role:
    name: common
    tasks_from: nginx_app_setup.yaml

- name: Enable the Nginx module stream and install the package
  ansible.builtin.dnf:
    name: "@nginx:1.24/server" # Use the correct module:stream/profile for your system.
    state: present
    become: true

- name: copy the service file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Reload systemd and restart nginx
