- name: Start, enable & daemon-reload shipping service
  ansible.builtin.systemd:
    name: shipping
    daemon_reload: yes
    state: restarted #why we are restaring if its running it will restart.
    enabled: yes
