- name: Start, enable & daemon-reload user service
  ansible.builtin.systemd:
    name: user
    daemon_reload: yes
    state: restarted #why we are restaring if its running it will restart.
    enabled: yes
