- name: "Reload systemd and restart payment"
  ansible.builtin.systemd:
    name: payment
    daemon_reload: yes
    state: restarted #why we are restaring if its running it will restart.
    enabled: yes
