- name: Install Maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - maven
    - mysql

- name: Install the dependencies
  tags:
    - deployment
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app
