- name: Install python3
  community.general.easy_install:
    name: "{{ item }}"
    state: latest
  loop:
    - python
    - gcc
    - python-devel

- name: Install the dependencies
  ansible.builtin.pip:
    requirements: requirements.txt # Directory containing requirements.txt
    executable: pip3.9
#code
