- name: Install python3
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - python
    - gcc
    - python-devel

- name: install dependencie
  tags:
    - deployment
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app
